### ISSUE TITLE
stealing stickers slowly 

### ISSUE THREAD

**Issue by FlareHD** [Glazelf/.github#7]
### Issue Description

i can’t steal a gif sticker of glaze hanging himself in game.

### Expected Behaviour

to be able to commit digital theft

### Reproduction

click the sticker
no steal

### Device Info

idfk

### Issue Priority

Medium (Low impact for many or all users)

**Comment by Glazelf** [comment]
Issue supposed to be in https://github.com/Glazelf/NinigiBot.
